// Stable transport names recovered from the existing worker modules.
// Keep these strings stable while the implementation is moved out of bundle.worker.js.

export const COMMANDS = Object.freeze({
  INITIALIZE_GAME: 'initialize-game',
  LOAD_GAME: 'load-game',
  RESET_GAME: 'reset-game',
  START_TICKING: 'start-ticking',
  GET_SAVE_STRING: 'get-save-string',

  QUERY_UNLOCKS: 'query-unlocks',
  QUERY_RESOURCES: 'query-resources-data',
  SET_RESOURCE_PINNED: 'set-resource-pinned',
  QUERY_ALL_RESOURCES: 'query-all-resources',
  QUERY_ATTRIBUTES: 'query-attributes-data',
  QUERY_ATTRIBUTES_UNLOCKS: 'query-attributes-unlocks',
  QUERY_ALL_ATTRIBUTES: 'query-all-attributes',
  QUERY_MAGE: 'query-mage-data',

  QUERY_ACTIONS: 'query-actions-data',
  QUERY_ALL_ACTIONS: 'query-all-actions',
  QUERY_ACTION_TAGS: 'query-all-action-tags',
  QUERY_ACTION_UNLOCKS: 'query-actions-unlocks',
  QUERY_ACTION_DETAILS: 'query-action-details',
  QUERY_ACTION_XP_BREAKDOWN: 'query-action-xp-breakdown',
  QUERY_ACTIONS_RUNNING: 'query-actions-running',
  RUN_ACTION: 'run-action',
  TOGGLE_HIDDEN_ACTION: 'toggle-hidden-action',
  TOGGLE_SHOW_HIDDEN: 'toggle-show-hidden',
  SET_SELECTED_ACTIONS_FILTER: 'set-selected-actions-filter',
  SET_ACTIONS_SEARCH: 'set-actions-search',
  SET_ACTION_ASPECT_LEVEL: 'set-action-aspect-level',
  TOGGLE_ACTION_ASPECT_MAXED: 'toggle-action-aspect-maxed',
  ACTIONS_CHANGE_CUSTOM_FILTERS_ORDER: 'actions-change-custom-filters-order',
  SAVE_ACTIONS_CUSTOM_FILTER: 'save-actions-custom-filter',
  DELETE_ACTIONS_CUSTOM_FILTER: 'delete-actions-custom-filter',
  TOGGLE_ACTIONS_CUSTOM_FILTER_PINNED: 'toggle-actions-custom-filter-pinned',
  APPLY_ACTIONS_CUSTOM_FILTER: 'apply-actions-custom-filter',

  QUERY_ACTIONS_LISTS: 'query-actions-lists',
  QUERY_ACTION_LIST_EFFECTS: 'query-action-list-effects',
  SAVE_ACTION_LIST: 'save-action-list',
  DELETE_ACTION_LIST: 'delete-action-list',
  LOAD_ACTION_LIST: 'load-action-list',
  RUN_LIST: 'run-list',
  STOP_LIST: 'stop-list',
  SET_ACTION_LISTS_ORDER: 'set-action-lists-order',
  SET_AUTOMATION_ENABLED: 'set-automation-enabled',
  SET_AUTOTRIGGER_INTERVAL: 'set-autotrigger-interval',

  QUERY_INVENTORY: 'query-inventory-data',
  QUERY_INVENTORY_DETAILS: 'query-inventory-details',
  QUERY_SELL_DETAILS: 'query-sell-details',
  SELL_INVENTORY: 'sell-inventory',
  CONSUME_INVENTORY: 'consume-inventory',
  SET_INVENTORY_SEARCH: 'set-inventory-search',
  SET_SELECTED_INVENTORY_FILTER: 'set-selected-inventory-filter',
  SAVE_INVENTORY_SETTINGS: 'save-inventory-settings',

  QUERY_COURSES: 'query-course-data',
  QUERY_COURSE_DETAILS: 'query-course-details',
  SET_COURSE_AUTOPURCHASE: 'set-course-autopurchase',
  RUN_COURSE: 'run-course',
  STOP_COURSE: 'stop-course',

  TOGGLE_SPEEDUP: 'toggle-speedup',
  QUERY_SETTINGS: 'query-settings',
  SET_SETTING: 'set-setting',
  QUERY_TOUR_STATUS: 'query_tour_status',
  SET_TOUR_FINISHED: 'set_tour_finished',
  QUERY_SKILLS: 'query-skills-data',
  PURCHASE_SKILL: 'purchase-skill',
  REMOVE_SKILL: 'remove-skill',
  APPLY_SKILL_CHANGES: 'apply-skill-changes',
  DISCARD_SKILL_CHANGES: 'discard-skill-changes',
  QUERY_ACTIVE_EFFECTS: 'query-active-effects',
  QUERY_STATISTICS: 'query-statistics',
  QUERY_TOTAL_UNLOCKS: 'query-total-unlocks',
  SAVE_SKILL_DRAFT: 'save-skill-draft',
  LOAD_SKILL_DRAFT: 'load-skill-draft',
  DELETE_SKILL_DRAFT: 'delete-skill-draft',
  EXPORT_SKILL_DRAFT: 'export-skill-draft',
  IMPORT_SKILL_DRAFT: 'import-skill-draft',

  PURCHASE_ITEM: 'purchase-item',
  PURCHASE_RESOURCE: 'purchase-resource',
  SET_PURCHASE_MULTIPLIER: 'set-purchase-multiplier',
  QUERY_ITEMS: 'query-items-data',
  QUERY_ITEM_DETAILS: 'query-item-details',
  QUERY_ITEMS_RESOURCES: 'query-items-resources-data',
  QUERY_ITEM_RESOURCE_DETAILS: 'query-item-resource-details',
  QUERY_GENERAL_SHOP_STATS: 'query-general-shop-stats',
  SET_SHOP_AUTO_PURCHASE: 'set-shop-autopurchase',
  SET_SHOP_SHOW_MAXED: 'set-shop-show-maxed',

  QUERY_FURNITURES: 'query-furnitures-data',
  QUERY_FURNITURE_DETAILS: 'query-furniture-details',
  QUERY_GENERAL_PROPERTY_STATS: 'query-general-property-stats',
  SET_FURNITURE_AUTO_PURCHASE: 'set-furniture-autopurchase',
  PURCHASE_FURNITURE: 'purchase-furniture',
  SET_FURNITURE_HIDE_MAXED: 'set-furniture-hide-maxed',
  SET_FURNITURE_SEARCH: 'set-furniture-search-text',
  SAVE_PROPERTY_CUSTOM_FILTER: 'save-property-custom-filter',
  DELETE_PROPERTY_CUSTOM_FILTER: 'delete-property-custom-filter',
  TOGGLE_PROPERTY_CUSTOM_FILTER_PINNED: 'toggle-property-custom-filter-pinned',
  APPLY_PROPERTY_CUSTOM_FILTER: 'apply-property-custom-filter',
  QUERY_ALL_FURNITURE_TAGS: 'query-all-furniture-tags',
  QUERY_ALL_ACCESSORY_TAGS: 'query-all-accessory-tags',
  QUERY_ALL_PROPERTY_EFFECTS: 'query-all-property-effects',

  QUERY_CRAFTING: 'query-crafting-data',
  QUERY_CRAFTING_DETAILS: 'query-crafting-details',
  QUERY_CRAFTING_GENERAL: 'query-crafting-general-data',
  SET_CRAFTING_LEVEL: 'set-crafting-level',
  QUERY_PLANTATION: 'query-plantation-data',
  QUERY_PLANTATION_DETAILS: 'query-plantation-details',
  SET_PLANTATION_AUTO_PURCHASE: 'set-plantation-autopurchase',
  PURCHASE_PLANTATION: 'purchase-plantation',
  SET_PLANTATION_WATERING: 'set-plantation-watering',
  REMOVE_PLANTATION: 'remove-plantation',

  QUERY_SPELLS: 'query-spell-data',
  QUERY_SPELL_DETAILS: 'query-spell-details',
  GET_SPELL_LEVEL_EFFECTS: 'get-spell-level-effects',
  SAVE_SPELL_SETTINGS: 'save-spell-settings',
  QUERY_ALL_SPELLS: 'query-all-spells',
  QUERY_GENERAL_MAGIC_STATS: 'query-general-magic-stats',
  USE_SPELL: 'use-spell',

  QUERY_GUILD_ITEMS: 'query-guild-items-data',
  QUERY_GUILD_ITEM_DETAILS: 'query-guild-item-details',
  QUERY_ALL_GUILDS_EFFECTS: 'query-all-guilds-effects',
  SELECT_GUILD: 'select-guild',
  LEAVE_GUILD: 'leave-guild',
  PURCHASE_GUILD_ITEM: 'purchase-guild-item',

  QUERY_MAP: 'query-map-data',
  MAP_HIGHLIGHT_FILTER: 'map-highlight-filter',
  QUERY_MAP_HIGHLIGHTED_TILES: 'query-map-list-highlighted-tiles',
  MAP_HIGHLIGHT_RESOURCES: 'map-highlight-resources',
  MAP_SET_GENERATED_LEVEL: 'map-set-generated-level',
  MAP_QUERY_GENERAL_DATA: 'map-query-general-data',
  MAP_GENERATE_MAP: 'map-generate-map',
  QUERY_MAP_TILE_DETAILS: 'query-map-tile-details',
  TOGGLE_MAP_TILE_RUNNING: 'toggle-map-tile-running',

  QUERY_EVENT_DATA: 'query-event-data',
  SET_EVENT_DATA_OPENED: 'set-event-data-opened',
  SELECT_EVENT_OPTION: 'select-event-option',

  QUERY_ALL_HOTKEYS: 'query-all-hotkeys',
  UPDATE_HOTKEY: 'update-hotkey',
  SET_MONITORED: 'set-monitored',
  CHECK_RULE_CONDITIONS_MATCHED: 'check-rule-conditions-matched',
});

export const EVENTS = Object.freeze({
  INITIALIZED: 'initialized',
  UNLOCKS: 'unlocks',
  RESOURCES: 'resources-data',
  ATTRIBUTES: 'attributes-data',
  MAGE_DATA: 'mage-data-banked',
  ACTIONS: 'actions-data',
  ACTIONS_RUNNING: 'actions-running',
  ACTIONS_LISTS: 'actions-lists',
  ACTION_DETAILS: 'action-details',
  INVENTORY: 'inventory-data',
  INVENTORY_DETAILS: 'detail-blade-inventory-details',
  SELL_DETAILS: 'sell-details',
  COURSE_DATA: 'items-data',
  SKILLS: 'skills-data',
  SKILL_DRAFT_ERROR: 'import-skill-draft-error',
  SKILL_DRAFT_BLOB: 'export-skill-draft-blob',
  EVENT_DATA: 'event-data',
});

export function assertKnownCommand(command) {
  if (!Object.values(COMMANDS).includes(command)) {
    throw new Error(`Unknown game command: ${command}`);
  }
}
